# Generated by Django 3.2.25 on 2026-02-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activiteit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('begin_tijd', models.TimeField()),
                ('eind_tijd', models.TimeField()),
                ('omschrijving', models.TextField()),
                ('kosten', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
